DELETE http://localhost:3001/api/persons/689

###
POST http://localhost:3003/api/persons
Content-Type: application/json

{
    "name": "Does it GET",
    "phone": "You"
}


###
GET http://localhost:3001/api/persons/4
